/**
 * Kenyan artifacts catalogue — real craft types paired with real Kenya shops
 */
window.AuroraTravels = window.AuroraTravels || {};

window.AuroraTravels.artifacts = [
  {
    id: "maasai-beaded-collar",
    title: "MAASAI BEADED COLLAR",
    shortTitle: "Maasai Collar",
    category: "Jewelry | Beadwork | Heritage",
    price: 4500,
    currency: "KES",
    rating: 4,
    desc: "Hand-strung Maasai beaded collar in traditional colour bands. Crafted by women artisans in Narok and sold through Nairobi's Maasai Market collective — each piece carries clan colour language and living pastoral tradition.",
    hero: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=1600&q=80&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400&q=75&auto=format&fit=crop",
    shop: {
      name: "Maasai Market — Junction / Village Market",
      city: "Nairobi",
      maps: "https://www.google.com/maps/search/?api=1&query=Maasai+Market+Village+Market+Nairobi",
    },
  },
  {
    id: "kisii-soapstone-mask",
    title: "KISII SOAPSTONE MASK",
    shortTitle: "Soapstone Mask",
    category: "Sculpture | Kisii | Carving",
    price: 6200,
    currency: "KES",
    rating: 5,
    desc: "Hand-carved soapstone mask from Tabaka, Kisii County. Soft stone takes fine facial planes and ochre polish — a signature export craft of western Kenya, finished by family workshops that have worked this rock for generations.",
    hero: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600&q=80&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=75&auto=format&fit=crop",
    shop: {
      name: "Kisii Soapstone Cooperative — Tabaka",
      city: "Kisii",
      maps: "https://www.google.com/maps/search/?api=1&query=Tabaka+Soapstone+Kisii+Kenya",
    },
  },
  {
    id: "maasai-spear-shield",
    title: "MAASAI SPEAR & SHIELD",
    shortTitle: "Spear & Shield",
    category: "Weapons | Ceremony | Leather",
    price: 12500,
    currency: "KES",
    rating: 4,
    desc: "Ceremonial Maasai spear paired with a painted rawhide shield. Produced for cultural display and heritage collections — the oval shield geometry and red-white-black motifs echo warrior age-set symbolism across the Rift.",
    hero: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1600&q=80&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=400&q=75&auto=format&fit=crop",
    shop: {
      name: "African Heritage House Gallery Shop",
      city: "Nairobi",
      maps: "https://www.google.com/maps/search/?api=1&query=African+Heritage+House+Nairobi",
    },
  },
  {
    id: "akamba-ebony-carving",
    title: "AKAMBA EBONY FIGURE",
    shortTitle: "Ebony Figure",
    category: "Wood | Akamba | Sculpture",
    price: 8900,
    currency: "KES",
    rating: 5,
    desc: "Dense ebony figure carved by Akamba artisans in Wamunyu, Machakos. Known worldwide for polished animal and human forms, this cooperative village remains Kenya's most famous wood-carving centre.",
    hero: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1600&q=80&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&q=75&auto=format&fit=crop",
    shop: {
      name: "Akamba Handicraft Industry Cooperative",
      city: "Wamunyu, Machakos",
      maps: "https://www.google.com/maps/search/?api=1&query=Akamba+Handicraft+Cooperative+Wamunyu",
    },
  },
  {
    id: "kazuri-bead-bracelet",
    title: "KAZURI BEAD BRACELET",
    shortTitle: "Kazuri Beads",
    category: "Jewelry | Ceramic | Fair Trade",
    price: 2800,
    currency: "KES",
    rating: 5,
    desc: "Glazed ceramic bead bracelet from Kazuri Beads in Karen, Nairobi — a women-led fair-trade workshop founded in 1975. Each bead is rolled, fired and strung on site overlooking the Ngong Hills.",
    hero: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=1600&q=80&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&q=75&auto=format&fit=crop",
    shop: {
      name: "Kazuri Beads Factory & Shop",
      city: "Karen, Nairobi",
      maps: "https://www.google.com/maps/search/?api=1&query=Kazuri+Beads+Karen+Nairobi",
    },
  },
  {
    id: "kiondo-sisal-basket",
    title: "KIONDO SISAL BASKET",
    shortTitle: "Kiondo Basket",
    category: "Weaving | Sisal | Utility",
    price: 3500,
    currency: "KES",
    rating: 4,
    desc: "Hand-woven kiondo of sisal and leather handles — Kenya's iconic market basket. Made by women's weaving groups around Nairobi and sold through city craft markets and cooperative stalls.",
    hero: "https://images.unsplash.com/photo-1590736969955-71cc94901144?w=1600&q=80&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1590736969955-71cc94901144?w=400&q=75&auto=format&fit=crop",
    shop: {
      name: "City Market Craft Stalls",
      city: "Nairobi CBD",
      maps: "https://www.google.com/maps/search/?api=1&query=City+Market+Nairobi+Kenya",
    },
  },
  {
    id: "makonde-inspired-mask",
    title: "COASTAL WOODEN MASK",
    shortTitle: "Coastal Mask",
    category: "Mask | Wood | Swahili Coast",
    price: 7800,
    currency: "KES",
    rating: 4,
    desc: "Hand-finished wooden mask from Lamu and Mombasa coast workshops — Swahili and Makonde-influenced carving traditions traded along the Indian Ocean for centuries, still shaped in island and mainland ateliers.",
    hero: "https://images.unsplash.com/photo-1551913902-c92207326525?w=1600&q=80&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1551913902-c92207326525?w=400&q=75&auto=format&fit=crop",
    shop: {
      name: "Lamu Old Town Craft Shops",
      city: "Lamu Island",
      maps: "https://www.google.com/maps/search/?api=1&query=Lamu+Old+Town+Handicrafts+Kenya",
    },
  },
  {
    id: "gourd-calabash-art",
    title: "ENGRAVED CALABASH",
    shortTitle: "Calabash Art",
    category: "Gourd | Engraving | Utility",
    price: 2200,
    currency: "KES",
    rating: 4,
    desc: "Engraved calabash gourd used across Kenyan communities for milk and ceremony. Decorative pyrography and bead trim turn a daily vessel into a collectible — sourced from Rift Valley craft traders.",
    hero: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=1600&q=80&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&q=75&auto=format&fit=crop",
    shop: {
      name: "Banana Hill Art Gallery",
      city: "Banana Hill, Kiambu",
      maps: "https://www.google.com/maps/search/?api=1&query=Banana+Hill+Art+Gallery+Kenya",
    },
  },
];
