/**
 * Page 1 — National parks: Kenya (10) + major parks across Africa
 */
window.AuroraTravels = window.AuroraTravels || {};

function park({
  name,
  region,
  coord,
  dist,
  ext,
  loc,
  desc,
  img,
  mapQ,
  lat,
  lng,
  zoom = 10,
  stops,
}) {
  return {
    name,
    region,
    coord,
    dist,
    ext,
    loc,
    desc,
    img,
    thumb: img.replace("w=1600", "w=200").replace("q=80", "q=70"),
    mapQ,
    lat,
    lng,
    zoom,
    stops,
  };
}

window.AuroraTravels.destinations = [
  /* ——— Kenya (10) ——— */
  park({
    name: "Maasai Mara",
    region: "Narok County, Kenya",
    coord: "1.5000° S 35.1435° E",
    dist: "≋ 270 km from Nairobi",
    ext: "Extension: 1,510 km²",
    loc: "Location: Great Rift Valley, southwestern Kenya",
    desc: "Kenya's flagship reserve and the northern reach of the Serengeti ecosystem. Home to the Great Migration, Big Five sightings and living Maasai culture along the Mara River.",
    img: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1600&q=80&auto=format&fit=crop",
    mapQ: "Maasai+Mara+National+Reserve",
    lat: -1.5,
    lng: 35.1435,
    stops: [
      { name: "Mara River Crossing", lat: -1.581, lng: 35.183 },
      { name: "Talek Gate", lat: -1.455, lng: 35.235 },
      { name: "Maasai Cultural Village", lat: -1.41, lng: 35.07 },
    ],
  }),
  park({
    name: "Amboseli",
    region: "Kajiado County, Kenya",
    coord: "2.6527° S 37.2606° E",
    dist: "≋ 240 km from Nairobi",
    ext: "Extension: 392 km²",
    loc: "Location: Foot of Mt Kilimanjaro, southern Kenya",
    desc: "Open plains and swamp systems framed by Kilimanjaro. Famous for large elephant herds, Maasai communities and some of East Africa's most iconic photographic horizons.",
    img: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1600&q=80&auto=format&fit=crop",
    mapQ: "Amboseli+National+Park",
    lat: -2.6527,
    lng: 37.2606,
    stops: [
      { name: "Observation Hill", lat: -2.665, lng: 37.248 },
      { name: "Kimana Gate", lat: -2.74, lng: 37.32 },
      { name: "Enkongo Narok Swamp", lat: -2.64, lng: 37.27 },
    ],
  }),
  park({
    name: "Tsavo East",
    region: "Taita-Taveta / Kitui, Kenya",
    coord: "2.9833° S 38.4667° E",
    dist: "≋ 300 km from Nairobi",
    ext: "Extension: 13,747 km²",
    loc: "Location: Southeast Kenya, Galana River corridor",
    desc: "One of the world's largest parks — red-dust elephants, arid bush and the Yatta Plateau. A classic Kenya safari landscape of space and silence.",
    img: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1600&q=80&auto=format&fit=crop",
    mapQ: "Tsavo+East+National+Park",
    lat: -2.9833,
    lng: 38.4667,
    zoom: 9,
    stops: [
      { name: "Aruba Dam", lat: -3.05, lng: 38.5 },
      { name: "Mudanda Rock", lat: -3.02, lng: 38.55 },
      { name: "Voi Gate", lat: -3.38, lng: 38.57 },
    ],
  }),
  park({
    name: "Tsavo West",
    region: "Taita-Taveta, Kenya",
    coord: "3.3167° S 38.0667° E",
    dist: "≋ 240 km from Nairobi",
    ext: "Extension: 9,065 km²",
    loc: "Location: Southeast Kenya, Mzima Springs & Chyulu foothills",
    desc: "Volcanic hills, rhino sanctuary country and crystal Mzima Springs. More varied terrain than Tsavo East, with lava flows and verdant waterholes.",
    img: "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=1600&q=80&auto=format&fit=crop",
    mapQ: "Tsavo+West+National+Park",
    lat: -3.3167,
    lng: 38.0667,
    zoom: 9,
    stops: [
      { name: "Mzima Springs", lat: -3.02, lng: 38.11 },
      { name: "Ngulia Rhino Sanctuary", lat: -3.05, lng: 38.15 },
      { name: "Shetani Lava Flow", lat: -2.95, lng: 37.98 },
    ],
  }),
  park({
    name: "Lake Nakuru",
    region: "Nakuru County, Kenya",
    coord: "0.3667° S 36.0833° E",
    dist: "≋ 160 km from Nairobi",
    ext: "Extension: 188 km²",
    loc: "Location: Great Rift Valley, central Kenya",
    desc: "A compact Rift Valley park known for flamingos, rhinos and lakeshore game drives. Easy access from Nairobi makes it a classic Kenya circuit stop.",
    img: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1600&q=80&auto=format&fit=crop",
    mapQ: "Lake+Nakuru+National+Park",
    lat: -0.3667,
    lng: 36.0833,
    stops: [
      { name: "Baboon Cliff", lat: -0.35, lng: 36.08 },
      { name: "Makalia Falls", lat: -0.42, lng: 36.1 },
      { name: "Main Gate", lat: -0.3, lng: 36.1 },
    ],
  }),
  park({
    name: "Aberdare",
    region: "Nyandarua / Nyeri, Kenya",
    coord: "0.4167° S 36.7000° E",
    dist: "≋ 150 km from Nairobi",
    ext: "Extension: 766 km²",
    loc: "Location: Central Highlands, Kenya",
    desc: "Misty moorlands, waterfalls and dense forest — a highland contrast to savanna parks. Historic Treetops and The Ark sit on its wildlife trails.",
    img: "https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?w=1600&q=80&auto=format&fit=crop",
    mapQ: "Aberdare+National+Park",
    lat: -0.4167,
    lng: 36.7,
    stops: [
      { name: "Karuru Falls", lat: -0.45, lng: 36.72 },
      { name: "Wandare Gate", lat: -0.38, lng: 36.78 },
      { name: "Salient", lat: -0.35, lng: 36.85 },
    ],
  }),
  park({
    name: "Mount Kenya",
    region: "Central Highlands, Kenya",
    coord: "0.1521° S 37.3084° E",
    dist: "≋ 175 km from Nairobi",
    ext: "Extension: 715 km²",
    loc: "Location: Central Kenya, on the Equator",
    desc: "Africa's second-highest peak and a UNESCO site. Afro-alpine flora, sacred Kirinyaga lore and trek routes to Point Lenana.",
    img: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80&auto=format&fit=crop",
    mapQ: "Mount+Kenya+National+Park",
    lat: -0.1521,
    lng: 37.3084,
    zoom: 11,
    stops: [
      { name: "Point Lenana", lat: -0.1522, lng: 37.3103 },
      { name: "Sirimon Gate", lat: -0.0289, lng: 37.2306 },
      { name: "Naro Moru Trailhead", lat: -0.166, lng: 37.197 },
    ],
  }),
  park({
    name: "Hell's Gate",
    region: "Nakuru County, Kenya",
    coord: "0.8667° S 36.3167° E",
    dist: "≋ 90 km from Nairobi",
    ext: "Extension: 68 km²",
    loc: "Location: Near Lake Naivasha, Rift Valley",
    desc: "Dramatic gorges, geothermal vents and cycling/walking game viewing — a rare Kenya park where you explore on foot or bike among zebra and giraffe.",
    img: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1600&q=80&auto=format&fit=crop",
    mapQ: "Hells+Gate+National+Park+Kenya",
    lat: -0.8667,
    lng: 36.3167,
    stops: [
      { name: "Fischer's Tower", lat: -0.87, lng: 36.32 },
      { name: "Lower Gorge", lat: -0.9, lng: 36.33 },
      { name: "Elsa Gate", lat: -0.85, lng: 36.31 },
    ],
  }),
  park({
    name: "Samburu",
    region: "Samburu County, Kenya",
    coord: "0.5686° N 37.5364° E",
    dist: "≋ 350 km from Nairobi",
    ext: "Extension: 165 km²",
    loc: "Location: Northern Kenya, Ewaso Nyiro River",
    desc: "Semi-arid north Kenya with rare 'Samburu Special Five' — grevy's zebra, reticulated giraffe, Somali ostrich, gerenuk and beisa oryx.",
    img: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1600&q=80&auto=format&fit=crop",
    mapQ: "Samburu+National+Reserve",
    lat: 0.5686,
    lng: 37.5364,
    stops: [
      { name: "Ewaso Nyiro River", lat: 0.57, lng: 37.54 },
      { name: "Koitogor Hill", lat: 0.55, lng: 37.55 },
      { name: "Archer's Post Gate", lat: 0.64, lng: 37.68 },
    ],
  }),
  park({
    name: "Meru",
    region: "Meru County, Kenya",
    coord: "0.1000° N 38.2000° E",
    dist: "≋ 350 km from Nairobi",
    ext: "Extension: 870 km²",
    loc: "Location: Eastern Kenya, below the Nyambene Hills",
    desc: "Lush, less-visited park of Elsa the lioness fame. Rivers, rhino sanctuary and wild bush that feels remote even on a Kenya circuit.",
    img: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1600&q=80&auto=format&fit=crop",
    mapQ: "Meru+National+Park",
    lat: 0.1,
    lng: 38.2,
    stops: [
      { name: "Rhino Sanctuary", lat: 0.12, lng: 38.18 },
      { name: "Murera Gate", lat: 0.15, lng: 38.1 },
      { name: "Tana River", lat: 0.05, lng: 38.25 },
    ],
  }),
  /* ——— Major Africa ——— */
  park({
    name: "Serengeti",
    region: "Northern Tanzania",
    coord: "2.3333° S 34.8333° E",
    dist: "≋ Shared border with Maasai Mara",
    ext: "Extension: 14,750 km²",
    loc: "Location: Northern Tanzania, East Africa",
    desc: "The southern half of the migration ecosystem. Endless plains, predator density and one of Africa's greatest wildlife spectacles.",
    img: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1600&q=80&auto=format&fit=crop&sat=-10",
    mapQ: "Serengeti+National+Park",
    lat: -2.3333,
    lng: 34.8333,
    zoom: 8,
    stops: [
      { name: "Seronera Valley", lat: -2.43, lng: 34.82 },
      { name: "Ndutu", lat: -3.0, lng: 35.0 },
      { name: "Lobo Area", lat: -1.9, lng: 35.0 },
    ],
  }),
  park({
    name: "Kruger",
    region: "Limpopo / Mpumalanga, South Africa",
    coord: "24.0000° S 31.5000° E",
    dist: "≋ Southern Africa flagship",
    ext: "Extension: 19,485 km²",
    loc: "Location: Northeast South Africa",
    desc: "Africa's most developed self-drive safari park — Big Five, rest camps and vast bushveld from the Limpopo to Crocodile River.",
    img: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1600&q=80&auto=format&fit=crop&hue=10",
    mapQ: "Kruger+National+Park",
    lat: -24.0,
    lng: 31.5,
    zoom: 7,
    stops: [
      { name: "Skukuza", lat: -24.99, lng: 31.59 },
      { name: "Satara", lat: -24.39, lng: 31.78 },
      { name: "Punda Maria", lat: -22.68, lng: 31.02 },
    ],
  }),
  park({
    name: "Chobe",
    region: "Northern Botswana",
    coord: "18.0000° S 24.5000° E",
    dist: "≋ Near Victoria Falls corridor",
    ext: "Extension: 11,700 km²",
    loc: "Location: Northern Botswana, Chobe River",
    desc: "Riverfront elephant concentrations among the densest in Africa, with boat safaris and floodplain game viewing.",
    img: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1600&q=80&auto=format&fit=crop&sat=-15",
    mapQ: "Chobe+National+Park",
    lat: -18.0,
    lng: 24.5,
    zoom: 8,
    stops: [
      { name: "Chobe Riverfront", lat: -17.82, lng: 25.15 },
      { name: "Savuti", lat: -18.57, lng: 24.07 },
      { name: "Ngoma Gate", lat: -17.92, lng: 24.72 },
    ],
  }),
  park({
    name: "Volcanoes NP",
    region: "Northern Rwanda",
    coord: "1.4833° S 29.5000° E",
    dist: "≋ Virunga gorilla highlands",
    ext: "Extension: 160 km²",
    loc: "Location: Northwest Rwanda, Virunga Massif",
    desc: "Mountain gorilla trekking in bamboo and volcano slopes — a cornerstone of African primate tourism and conservation.",
    img: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1600&q=80&auto=format&fit=crop&sat=-25",
    mapQ: "Volcanoes+National+Park+Rwanda",
    lat: -1.4833,
    lng: 29.5,
    zoom: 11,
    stops: [
      { name: "Park HQ Kinigi", lat: -1.48, lng: 29.55 },
      { name: "Karisoke Area", lat: -1.46, lng: 29.49 },
      { name: "Bisoke Trail", lat: -1.47, lng: 29.48 },
    ],
  }),
  park({
    name: "Etosha",
    region: "Northern Namibia",
    coord: "18.8500° S 16.4333° E",
    dist: "≋ Namibian salt pan safari",
    ext: "Extension: 22,270 km²",
    loc: "Location: Northern Namibia",
    desc: "A vast salt pan ringed by waterholes — stark beauty, excellent game viewing and one of southern Africa's great self-drive parks.",
    img: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1600&q=80&auto=format&fit=crop&sat=-30",
    mapQ: "Etosha+National+Park",
    lat: -18.85,
    lng: 16.4333,
    zoom: 8,
    stops: [
      { name: "Okaukuejo", lat: -19.18, lng: 15.92 },
      { name: "Halali", lat: -19.03, lng: 16.47 },
      { name: "Namutoni", lat: -18.81, lng: 16.94 },
    ],
  }),
];
